# Main Application Configuration
server.port=8081

# Active profile - switched easily via .env variable ACTIVE_DB
spring.profiles.active=${ACTIVE_DB:supabase}

# JPA / Hibernate Common Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# View Configuration
spring.thymeleaf.cache=false